import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import {
  ClerkProvider,
  SignedIn,
  SignedOut,
  RedirectToSignIn,
} from "@clerk/nextjs";
import Navbar from "@/components/Navbar";
import Sidebar from "@/components/Sidebar";
import BottomNavbar from "@/components/BottomNavbar";
import { dark } from "@clerk/themes";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClerkProvider
        appearance={{
          baseTheme: dark,
        }}
      >
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased text-sm`}
        >
          <div className="flex text-zinc-200 h-dvh">
            {/* Handle SignedIn state */}
            <div className="flex bg-zinc-900 overflow-y-hidden w-full">

              <SignedIn>
                <div className="sidebar flex-none w-fit px-2 py-1 hidden md:block bg-zinc-800">
                  <Sidebar />
                </div>
              </SignedIn>
              <div className="grow">
                <SignedIn>
                  <Navbar />

                </SignedIn>
                {children}
              </div>
            </div>

            <div className="md:hidden block fixed bottom-0 z-10">
              <BottomNavbar />
            </div>

            {/* Handle SignedOut state */}
            <SignedOut>
              <RedirectToSignIn redirectUrl="/" />
            </SignedOut>
          </div>
        </body>
      </ClerkProvider>
    </html>
  );
}
